### ISSUE TITLE
Metroid Prime 1 - Door Lock Rando Fails to Apply Proper Blast Shield in Research Core Following Power Outage

### ISSUE THREAD

**Issue by BOB74j** [randovania/randomprime#33]
**Game**: Metroid Prime 1 (NTSC 0-00)
**Emulator**: Dolphin 5.0-21174 (Windows)
**Randovania**: 7.4.2 (Windows)

**Permalink**: DerUcq0uTokZ4BssjW3HVGhc8rTsTBI-lNjCAyI7HM7jqOd8vdz0yDKU9sCwJN5LuoTokXqDr-4AAN3f

In Metroid Prime 1 with door lock randomization enabled, some vanilla Wave Beam doors may be randomized as blast shield doors. This is the case in the included demonstration permalink, wherein the Wave Beam door in Phendrana Drifts - Research Core leading to Research Core Access has been shuffled to a Super Missile blast shield. However, when the item in Research Core is collected, leading to the power outage event, the blast shield fails to appear properly over the door. The blast shield is physically present and deflects all other weapons fire, but it cannot be scanned or visualized in any visor. The blast shield is invisible and can only be opened by knowing there "ought to be" a blast shield present, and firing a Super Missile accordingly.

**Steps to reproduce**:
1. Import the included demonstration permalink, or create a randomized Prime 1 world which randomizes Wave Beam doors to Super Missile blast shield doors.
2. Enter Research Core in Phendrana Drifts and collect the item therein.
3. The power will go out. Energize the energy conduit at the top of the room.
4. Attempt to open the door to Research Core Access. Though it appears to be a blue door, an invisible Super Missile blast shield is present which will deflect all other weapons fire.

**Expected behavior**: Any blast shield applied to the door leading from Research Core to Research Core Access should be visible, or failing that, disabled to prevent player confusion.

![GM8E01_2024-03-17_10-34-45](https://github.com/randovania/randovania/assets/43751378/aaa50672-95e5-4dcf-b2d5-0ea111276eec)
![GM8E01_2024-03-17_10-38-04](https://github.com/randovania/randovania/assets/43751378/9127063d-398e-41f4-8003-b30686cfc5bb)

**Comment by toasterparty** [comment]
Fixed
