### ISSUE TITLE
Softlock if you don't skip the Omega Pirate's death cutscene

### ISSUE THREAD

**Issue by FallenAngel34** [randovania/randomprime#53]
If you **don't** skip the Omega Pirate's death cutscene:
- Letterboxing and Samus' cutscene model won't go away.
- The doors and the elevator will stay locked, which essentially softlocks you in Elite Quarters.

This wasn't a thing on the patcher's versions 1.22.1 and below (the only issue in these versions is that the music doesn't start playing, just like in the vanilla 0-00).

![Dolphin Emulator Screenshot 2024 05 30 - 21 04 40 82](https://github.com/randovania/randomprime/assets/171281564/13bdd330-7d6c-490d-979a-e3aedd653052)

**Comment by MrMiguel211** [comment]
Will fix ASAP
