### ISSUE TITLE
Crash - Specific rooms can have "too many" blast shields

### ISSUE THREAD

**Issue by toasterparty** [randovania/randomprime#75]
The following rooms have caused an "alloc-failed" crash due to this:

## Biohazard Containment <--> Biotech Research Area 1
- Might need unlocked read speed for this crash
- IIRC the load triggers are not ideal here

## Central Dynamo
- We already remove all the debris in this room and adjacent. Will be tricky to find more to remove

**Comment by MrMiguel211** [comment]
Is this related to the crash Dan Salvato had? If so I should have made an issue about this earlier, but this memory issue could be fixed by changing these docks to not being auto loads and add load triggers to them.

**Comment by toasterparty** [comment]
Yeah Dan's issue.

The hard one is going to be Cen Dyna. We'll definitely change that frigate hallway to not be auto-load.

**Comment by MrMiguel211** [comment]
There other hallway is also an auto-load, that one needs to be changed as well
